### ISSUE TITLE
InApp browser show content on load finihed

### ISSUE THREAD

**Issue by Protoss78** [Tokencube/beacon-player#12]
Show content only when the whole content was loaded from the server (onLoadFinished event).

**Comment by Protoss78** [comment]
Show loading message or spinner

**Comment by BioPhoton** [comment]
the .hide() function not exist 
https://github.com/driftyco/ng-cordova/blob/master/demo/www/lib/ngCordova/dist/ng-cordova.js#L3327

so fo now we scip that
