### ISSUE TITLE
Handle bluetooth OFF situations

### ISSUE THREAD

**Issue by BioPhoton** [Tokencube/beacon-player#27]
alert even if app is running and user turs ble off

**Comment by Protoss78** [comment]
Only check if bluetooth is enabled, when the scan button is pushed. This cordova plugin can be used to check if bluetooth is enabled:
https://github.com/randdusing/BluetoothLE#isenabled

Make sure that whenever an onResume event is triggered, the same bluetooth logic is triggered as when the application is started for the first time.

**Comment by BioPhoton** [comment]
currently not supported
