### ISSUE TITLE
detect broken scan data

### ISSUE THREAD

**Issue by BioPhoton** [Tokencube/beacon-player#43]
no in the code following ifs for detectin broken scandata. What are you thinking about. and do you have some improvements?

if (!device && typeof device !== "object" || device === null) {
			console.log('toIsBrokenRawDevice returns false because the device is not a valis json object!');
			return false;
        }
		if (!(device.rssi <= 0)) {
			console.log('toIsBrokenRawDevice returns false because the device.rssi is not <= 0!');
			return false;
		}

**Comment by tokenofflineengine** [comment]
if(device.rssi >= 0) then ignore this as its not a plausible value
