### ISSUE TITLE
sometimes app exits on triggering emediately after starting

### ISSUE THREAD

**Issue by BioPhoton** [Tokencube/beacon-player#44]
guess problem is that we have to start scanning after inityally loading serverdata

**Comment by tokenofflineengine** [comment]
check if the lenght of beacon rawData is enough or try catch
https://github.com/Tokencube/beacon-player/blob/master/www/app/components/ble/services/ble-services.js#L575

**Comment by BioPhoton** [comment]
try time out befoer open IAB

**Comment by BioPhoton** [comment]
closed as this feature is not in releas for now
